### ISSUE TITLE
Would you update the latest version on chrome-extension store?

### ISSUE THREAD

**Issue by dohvis** [phonglk/slack-block-user-extension#6]
Would you update the latest version(v1.2.1) on chrome-extension store?

thanks for useful app :)

**Comment by veekas** [comment]
@dohvis FYI I [forked this repo](https://github.com/veekas/slack-block-user-extension) and published it [here](https://chrome.google.com/webstore/detail/slack-block-user-fork/dnopahhjengaejfdeleoohjdpmncjjlj) so that we could use this extension while waiting for a publish.

**Comment by phonglk** [comment]
Hi all, actually I was trying to publish v1.2.1 previously but got rejected.
I just tried again and the same outcome

```"User Data Privacy"

Your product violates the "Use of Permissions" section of the policy, which requires that you:

Request access to the narrowest permissions necessary to implement your product’s features or services.
If more than one permission could be used to implement a feature, you must request those with the least access to data or functionality.
Don't attempt to "future proof" your product by requesting a permission that might benefit services or features that have not yet been implemented.
```

I will see how could I tackle this. If you guy have any suggestion, it is more than welcome!

**Comment by AmySteam** [comment]
Hi,
My name is Amy from [JackandAmydev](https://www.youtube.com/channel/UCVj3dGw75v8aHFYD6CL1tFg/) and we have helped many developers successfully publish their chrome extensions.
I went through your code, and you actually do NOT need the tabs permission. Its enough to use the host permissions and the content script.

Test the functionality without the tabs permission, and then try to publish to the webstore. If you have any more questions, feel free to DM at [@jackandamydev](https://twitter.com/JackandAmyDev)

Hope this helps,
Amy

**Comment by phonglk** [comment]
> Hi,
> My name is Amy from [JackandAmydev](https://www.youtube.com/channel/UCVj3dGw75v8aHFYD6CL1tFg/) and we have helped many developers successfully publish their chrome extensions.
> I went through your code, and you actually do NOT need the tabs permission. Its enough to use the host permissions and the content script.
> 
> Test the functionality without the tabs permission, and then try to publish to the webstore. If you have any more questions, feel free to DM at [@jackandamydev](https://twitter.com/JackandAmyDev)
> 
> Hope this helps,
> Amy

Thank @AmySteam, it's really helpful

**Comment by phonglk** [comment]
@dohvis Updated!

**Comment by AmySteam** [comment]
Sounds like you were approved at the store. Good luck with your extension. And please [support our channel by liking our videos](https://www.youtube.com/channel/UCVj3dGw75v8aHFYD6CL1tFg/), so that other developers can also benefit. Amy 🙋😄
